"""
Django settings for todo_django project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-y1u0*-0s&zp6i1pmvnbv2a@dy#&a5fqbe@@_k@waukh&t8&jj%"
SECRET_KEY = get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['simon2324.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tasks",
] 

# ========== SIMPLEUI CONFIGURATION ==========
# SIMPLEUI_CONFIG = {
#     'system_keep': False,
#     'menu_display': ['Tareas', 'Usuarios', 'Sitio'],
#     'dynamic': True,
#     'menus': [
#         {
#             'name': 'Tareas',
#             'icon': 'fas fa-tasks',
#             'models': [
#                 {
#                     'name': 'Ver Tareas',
#                     'icon': 'fas fa-list',
#                     'url': 'admin:tasks_task_changelist'
#                 }
#             ]
#         }
#     ]
# }

# Configuraciones PRINCIPALES de SimpleUI
SIMPLEUI_LOGO = '/static/admin/images/logo.png'  # Usa URL temporal
SIMPLEUI_SITE_TITLE = 'Task Manager Admin'
SIMPLEUI_SITE_HEADER = 'Task Manager - Administración'  # ¡ESTO FALTA!
SIMPLEUI_INDEX_TITLE = 'Panel de Control - Task Manager'
SIMPLEUI_HOME_TITLE = 'Dashboard Principal'
SIMPLEUI_HOME_ICON = 'fas fa-home'
SIMPLEUI_ANALYSIS = False  # Desactiva analytics
SIMPLEUI_HOME_INFO = False  # Oculta info
SIMPLEUI_HOME_QUICK = True  # Accesos rápidos
SIMPLEUI_HOME_ACTION = True  # Acciones rápidas

# Configuración del admin de Django (como respaldo)
from django.contrib.admin import AdminSite
AdminSite.site_title = "Task Manager Admin"
AdminSite.site_header = "Task Manager Administration"
AdminSite.index_title = "Panel de Control"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "todo_django.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "todo_django.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

LOGIN_URL = '/signin'
LOGIN_REDIRECT_URL = '/tasks/'
LOGOUT_REDIRECT_URL = '/'

ADMIN_LOGIN_URL = '/admin/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATIC_ROOT = BASE_DIR / 'static'
try:
    from .settings_dev import *
except ModuleNotFoundError:
    pass

